In [5]:
from project_heart.lv import LV
import numpy as np
import pyvista as pv
# import project_heart as ph
from project_heart.modules.geometry import Geometry
pv.set_jupyter_backend("pythreejs")

import os
from pathlib import Path

from project_heart.enums import *

In [6]:
filepath = Path("../sample_files/lvtetmesh_coarse_fibers_LDRB_1.vtk") 
lv_src = LV.from_pyvista_read(filepath)

filepath = Path("../sample_files/lvhexmesh.vtk") 
lv_dst = LV.from_pyvista_read(filepath)

In [44]:
lv_dst.regress_from_other_geometry(lv_src, 
                                   GEO_DATA.MESH_POINT_DATA, 
                                   LV_FIBERS.F0,
                                   hidden_layer_sizes=(100,50,100,50),
                                   verbose=True,
                                   validation_fraction=0.6,
                                   learning_rate='invscaling',
                                   )

Iteration 1, loss = 0.13857544
Validation score: 0.435160
Iteration 2, loss = 0.08627838
Validation score: 0.536478
Iteration 3, loss = 0.07023588
Validation score: 0.578431
Iteration 4, loss = 0.05819566
Validation score: 0.677073
Iteration 5, loss = 0.04403201
Validation score: 0.718517
Iteration 6, loss = 0.03777963
Validation score: 0.804244
Iteration 7, loss = 0.03190984
Validation score: 0.825268
Iteration 8, loss = 0.02874217
Validation score: 0.828167
Iteration 9, loss = 0.02790881
Validation score: 0.834049
Iteration 10, loss = 0.02553105
Validation score: 0.846239
Iteration 11, loss = 0.02379961
Validation score: 0.867246
Iteration 12, loss = 0.02255805
Validation score: 0.858611
Iteration 13, loss = 0.02146325
Validation score: 0.872881
Iteration 14, loss = 0.02006713
Validation score: 0.860476
Iteration 15, loss = 0.01944306
Validation score: 0.884996
Iteration 16, loss = 0.01868537
Validation score: 0.888259
Iteration 17, loss = 0.01845520
Validation score: 0.891957
Iterat

array([[-0.29707315,  0.63833693, -0.46798615],
       [-0.30924275,  0.654735  , -0.46861867],
       [-0.29538343,  0.65167938, -0.46245271],
       ...,
       [-0.05952181,  0.74231247,  0.53568141],
       [-0.1319518 ,  0.7859913 ,  0.466613  ],
       [-0.12328419,  0.79541355,  0.48665622]])

In [45]:
lv_dst.regress_from_other_geometry(lv_src, 
                                   GEO_DATA.MESH_POINT_DATA, 
                                   LV_FIBERS.S0,
                                   hidden_layer_sizes=(100,50,100,50),
                                   verbose=True,
                                   validation_fraction=0.6,
                                   learning_rate='invscaling',
                                   )

Iteration 1, loss = 0.13921136
Validation score: 0.219887
Iteration 2, loss = 0.10165954
Validation score: 0.290478
Iteration 3, loss = 0.09106865
Validation score: 0.367330
Iteration 4, loss = 0.08137451
Validation score: 0.435292
Iteration 5, loss = 0.06744063
Validation score: 0.574678
Iteration 6, loss = 0.05295828
Validation score: 0.642881
Iteration 7, loss = 0.03656936
Validation score: 0.790085
Iteration 8, loss = 0.02839201
Validation score: 0.717055
Iteration 9, loss = 0.02401537
Validation score: 0.846690
Iteration 10, loss = 0.02101944
Validation score: 0.857395
Iteration 11, loss = 0.01951138
Validation score: 0.853066
Iteration 12, loss = 0.01930344
Validation score: 0.852724
Iteration 13, loss = 0.01826351
Validation score: 0.866592
Iteration 14, loss = 0.01835526
Validation score: 0.862785
Iteration 15, loss = 0.01710824
Validation score: 0.852229
Iteration 16, loss = 0.01696495
Validation score: 0.875700
Iteration 17, loss = 0.01595317
Validation score: 0.877913
Iterat

array([[-0.55618551,  0.37559065,  0.50986744],
       [-0.54923776,  0.381707  ,  0.51080334],
       [-0.54636946,  0.38833738,  0.50249495],
       ...,
       [ 0.03128919, -0.53845971,  0.90396731],
       [-0.08379814, -0.51663482,  0.85576731],
       [-0.12223044, -0.51286402,  0.84353612]])

In [46]:
lv_dst.regress_from_other_geometry(lv_src, 
                                   GEO_DATA.MESH_POINT_DATA, 
                                   LV_FIBERS.N0,
                                   hidden_layer_sizes=(100,50,100,50),
                                   verbose=True,
                                   validation_fraction=0.6,
                                   learning_rate='invscaling',
                                   )

Iteration 1, loss = 0.05742680
Validation score: 0.910798
Iteration 2, loss = 0.01299704
Validation score: 0.925382
Iteration 3, loss = 0.01127935
Validation score: 0.932283
Iteration 4, loss = 0.01063461
Validation score: 0.934352
Iteration 5, loss = 0.01028737
Validation score: 0.935970
Iteration 6, loss = 0.00979015
Validation score: 0.937801
Iteration 7, loss = 0.00959471
Validation score: 0.940372
Iteration 8, loss = 0.00937947
Validation score: 0.941183
Iteration 9, loss = 0.00926853
Validation score: 0.942147
Iteration 10, loss = 0.00906057
Validation score: 0.941906
Iteration 11, loss = 0.00897392
Validation score: 0.941176
Iteration 12, loss = 0.00882299
Validation score: 0.944650
Iteration 13, loss = 0.00856578
Validation score: 0.944945
Iteration 14, loss = 0.00858423
Validation score: 0.945729
Iteration 15, loss = 0.00852087
Validation score: 0.945160
Iteration 16, loss = 0.00830301
Validation score: 0.943369
Iteration 17, loss = 0.00833769
Validation score: 0.948283
Iterat

array([[0.74017904, 0.5922402 , 0.27690487],
       [0.74451911, 0.58690502, 0.27238304],
       [0.74547263, 0.57612197, 0.28707471],
       ...,
       [0.9465644 , 0.00115389, 0.14599683],
       [0.9321151 , 0.12170468, 0.26867025],
       [0.92679392, 0.09518465, 0.28443541]])

In [47]:
lv_dst.identify_base_and_apex_surfaces() # computes normal
lv_dst.compute_fiber_angles()

In [50]:
lv_dst.plot_streamlines(LV_FIBERS.F0, scalars=LV_FIBERS.F0_ANGLES, decimate_boundary=0.8)

Renderer(camera=PerspectiveCamera(aspect=1.3333333333333333, children=(DirectionalLight(color='#fefefe', inten…

In [51]:
lv_dst.mesh.save("../sample_files/lvhex_with_fibers_test.vtk")

In [88]:
X = lv_src.points()
Y = lv_src.get(GEO_DATA.MESH_POINT_DATA, LV_FIBERS.F0)
XI = lv_dst.points()

In [89]:
Y.shape

(64452, 3)

In [91]:
Y1 = lv_src.get(GEO_DATA.MESH_POINT_DATA, LV_FIBERS.F0)
Y2 = lv_src.get(GEO_DATA.MESH_POINT_DATA, LV_FIBERS.S0)
Y3 = lv_src.get(GEO_DATA.MESH_POINT_DATA, LV_FIBERS.N0)
Y = np.hstack((Y1, Y2, Y3))
Y.shape

(64452, 9)

In [92]:
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import GradientBoostingRegressor

regr = MultiOutputRegressor(GradientBoostingRegressor(random_state=0, 
                                                      subsample=0.75,
                                                      n_estimators=200)).fit(X, Y)
YI = regr.predict(XI)

In [101]:
from sklearn.neural_network import MLPRegressor
MLPR = MLPRegressor((100,),
                    early_stopping=True,
                    validation_fraction=0.25,
                    )
MLPR = MLPR.fit(X, Y)
YI2 = MLPR.predict(XI)

In [95]:
lv_dst.mesh.point_data[LV_FIBERS.F0.value] = YI[:, :3]
lv_dst.mesh.point_data[LV_FIBERS.S0.value] = YI[:, 3:6]
lv_dst.mesh.point_data[LV_FIBERS.S0.value] = YI[:, 6:]

In [102]:
lv_dst.mesh.point_data[LV_FIBERS.F0.value] = YI2[:, :3]
lv_dst.mesh.point_data[LV_FIBERS.S0.value] = YI2[:, 3:6]
lv_dst.mesh.point_data[LV_FIBERS.S0.value] = YI2[:, 6:]

In [103]:
lv_dst.identify_base_and_apex_surfaces() # computes normal
lv_dst.compute_fiber_angles()

In [104]:
lv_dst.plot_streamlines(LV_FIBERS.F0, scalars=LV_FIBERS.F0_ANGLES, decimate_boundary=0.8)

Renderer(camera=PerspectiveCamera(aspect=1.3333333333333333, children=(DirectionalLight(color='#fefefe', inten…

In [72]:
lv_src.plot_streamlines(LV_FIBERS.F0, scalars=LV_FIBERS.F0_ANGLES, decimate_boundary=0.8)

Renderer(camera=PerspectiveCamera(aspect=1.3333333333333333, children=(DirectionalLight(color='#fefefe', inten…

In [79]:
lv_dst.mesh.save("./testhexfibers.vtk")