In [1]:
from project_heart.lv import LV
import numpy as np
import pyvista as pv
pv.set_jupyter_backend("pythreejs")

import os
from pathlib import Path

from project_heart.enums import *
import logging

float_formatter = "{:.5f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

In [2]:
filepath = Path("../sample_files/ellipsoid_2.stl")
lv = LV.from_file(filepath)
lv.set_geo_type(geo_type=LV_GEO_TYPES.IDEAL)

In [3]:
lv.identify_est_base_and_apex_regions(log_level=logging.DEBUG)

DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:Starting identification of base and apex regions.
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:Perfoming kmeans to find LV halves
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:kcenters: [[0.00002 0.00000 -48.78886]
 [-0.00000 -0.00000 0.32646]]
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:Estimating apex and base iteractively.
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:apex: [0.00000 0.00000 -72.69446]
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:base: [0.00000 0.00000 17.77086]
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:len(est_apex_region): 649
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:len(est_base_region): 1632


(pyvista_ndarray([19.00000, 19.00000, 19.00000, ..., 19.00000, 19.00000,
                  19.00000]),
 pyvista_ndarray([19.00000, 19.00000, 19.00000, ..., 19.00000, 19.00000,
                  19.00000]))

In [4]:
lv.plot("surface", 
        scalars=LV_MESH_DATA.APEX_BASE_EST,
        # container="points",
        show_edges=True,
        categorical=True,
        split_sharp_edges=True,
        smooth_shading=False,
        pretty=False,
        )

Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='#fefefe', position=(49999.9999…

In [5]:
lv.identify_epi_endo_regions(log_level=logging.DEBUG)

DEBUG:LV_RegionIdentifier.identify_epi_endo_regions:Starting identification of endo and epi regions for ideal geometry.
DEBUG:LV_RegionIdentifier.identify_epi_endo_regions:Using reference point: [0.00000 0.00000 -26.72786]
DEBUG:LV_RegionIdentifier.identify_epi_endo_regions:Number of endo ids found: 8449 (47.31%)
DEBUG:LV_RegionIdentifier.identify_epi_endo_regions:Number of epi ids found: 9409 (52.69%)


(pyvista_ndarray([2.00000, 2.00000, 2.00000, ..., 2.00000, 2.00000,
                  2.00000]),
 pyvista_ndarray([2.00000, 2.00000, 2.00000, ..., 2.00000, 2.00000,
                  2.00000]))

In [6]:
lv.plot("surface", 
        scalars=LV_MESH_DATA.EPI_ENDO,
        # container="points",
        show_edges=True,
        categorical=True,
        split_sharp_edges=True,
        smooth_shading=False,
        pretty=False,
        )

Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='#fefefe', position=(49999.9999…

In [7]:
lv.identify_base_region_ideal(log_level=logging.DEBUG)

DEBUG:LV_RegionIdentifier.identify_base_region_ideal:Starting identification of base region for ideal geometry.
DEBUG:LV_RegionIdentifier.identify_base_region_ideal:Number of edge points found: 192
DEBUG:LV_RegionIdentifier.identify_base_region_ideal:est_base: [0.00000 0.00000 20.00000]
DEBUG:LV_RegionIdentifier.identify_base_region_ideal:est_radius: 28.729089736833732
DEBUG:LV_RegionIdentifier.identify_base_region_ideal:Selecting points close to est_base based on 'd'.
DEBUG:LV_RegionIdentifier.identify_base_region_ideal:axis orientation: [2]
DEBUG:LV_RegionIdentifier.identify_base_region_ideal:number of indexed found at 'db=0.1' from 'est_base=[0.00000 0.00000 20.00000]'along 'axis=[2]'
DEBUG:LV_RegionIdentifier.identify_base_region_ideal:Filtering selection based on surface normals.
DEBUG:LV_RegionIdentifier.identify_base_region_ideal:Number of ioi found: 960
DEBUG:LV_RegionIdentifier.identify_base_region_ideal:Filtering selection based on surface endo region (no overlap).
DEBUG:LV_R

(pyvista_ndarray([2.00000, 2.00000, 2.00000, ..., 2.00000, 2.00000,
                  2.00000]),
 pyvista_ndarray([2.00000, 2.00000, 2.00000, ..., 2.00000, 2.00000,
                  2.00000]))

In [8]:
lv.plot("surface", 
        scalars=LV_MESH_DATA.SURFS,
        # container="points",
        show_edges=True,
        categorical=True,
        split_sharp_edges=True,
        smooth_shading=False,
        pretty=False,
        )

Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='#fefefe', position=(49999.9999…

In [9]:
lv.identify_regions_ideal(log_level=logging.DEBUG)

INFO:LV_RegionIdentifier.identify_regions_ideal:Identifying regions from ideal geometry.
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:Starting identification of base and apex regions.
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:Perfoming kmeans to find LV halves
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:kcenters: [[0.00002 0.00000 -48.78886]
 [-0.00000 -0.00000 0.32646]]
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:Estimating apex and base iteractively.
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:apex: [0.00000 0.00000 -72.69446]
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:base: [0.00000 0.00000 17.77086]
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:len(est_apex_region): 649
DEBUG:LV_RegionIdentifier.identify_base_and_apex_regions:len(est_base_region): 1632
DEBUG:LV_RegionIdentifier.identify_epi_endo_regions:Starting identification of endo and epi regions for ideal geometry.
DEBUG:LV_RegionIdentif

In [10]:
lv.plot("surface", 
        scalars=LV_MESH_DATA.SURFS_DETAILED,
        # container="points",
        show_edges=True,
        categorical=True,
        split_sharp_edges=True,
        smooth_shading=False,
        pretty=False,
        cmap="jet",
        vnodes=[[lv.VIRTUAL_NODES.BASE, {"color":"red"}], [lv.VIRTUAL_NODES.APEX, {"color":"green"}] ]
        )

Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='#fefefe', position=(49999.9999…

In [11]:
import logging
spk = lv.create_speckles(
        collection="test-base",
        group="base",
        name="test",
        from_nodeset=LV_SURFS.BASE,
        use_all_nodes=True,
        n_subsets=0,
        n_clusters=10,
        subsets_criteria="angles3",
        cluster_criteria="angles3",
        t=0.0,
        log_level=logging.DEBUG,
    )
lv.plot_speckles(spk, add_k_centers=True, k_bins=True, cmap="hot")

INFO:create_speckles:Speckle: name: test, group: base, collection: test-base
DEBUG:create_speckles:Using nodes from nodeset LV_SURFS.BASE
DEBUG:create_speckles:long_line: [[-0.00002 0.00001 -64.66667]
 [0.00000 0.00000 19.55463]]
DEBUG:create_speckles:ref p (spk center): [0.00000 0.00000 19.55463]
DEBUG:create_speckles:Using all nodes in mesh OR nodeset (not computing plane).
DEBUG:create_speckles:Adding single subset.
DEBUG:_subdivide_speckles:Subdividing Speckles into '10' buckets based on subsets_criteria: 'angles3'.
DEBUG:_subdivide_speckles:Number of buckets: 10.
DEBUG:_subdivide_speckles:pts.shape: (960, 3).
DEBUG:_subdivide_speckles:pts[:5]: 
[[26.76188 -20.53511 20.00000]
 [26.10436 -20.03058 20.00000]
 [25.30722 -22.19383 20.00000]
 [25.44683 -19.52604 20.00000]
 [24.06365 -21.10326 20.00000]].
DEBUG:_subdivide_speckles:plane_d: -19.554630279541016.
DEBUG:_subdivide_speckles:p_center: [0.00000 0.00000 19.55463].
DEBUG:_subdivide_speckles:ref_max_pt: 653.
DEBUG:_subdivide_speck

Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='#fefefe', position=(49999.9999…

In [13]:
import logging
spk = lv.create_speckles(
        collection="test-base",
        group="base",
        name="test-endo",
        from_nodeset=LV_SURFS.BASE_BORDER_ENDO,
        use_all_nodes=True,
        n_subsets=0,
        n_clusters=10,
        subsets_criteria="angles3",
        cluster_criteria="angles3",
        t=0.0,
        log_level=logging.DEBUG,
    )
lv.plot_speckles(spk, add_k_centers=True, k_bins=True, cmap="hot")

INFO:create_speckles:Speckle: name: test-endo, group: base, collection: test-base
DEBUG:create_speckles:Using nodes from nodeset LV_SURFS.BASE_BORDER_ENDO
DEBUG:create_speckles:long_line: [[-0.00002 0.00001 -64.66667]
 [0.00000 0.00000 19.55463]]
DEBUG:create_speckles:ref p (spk center): [0.00000 0.00000 19.55463]
DEBUG:create_speckles:Using all nodes in mesh OR nodeset (not computing plane).
DEBUG:create_speckles:Adding single subset.
DEBUG:_subdivide_speckles:Subdividing Speckles into '10' buckets based on subsets_criteria: 'angles3'.
DEBUG:_subdivide_speckles:Number of buckets: 10.
DEBUG:_subdivide_speckles:pts.shape: (96, 3).
DEBUG:_subdivide_speckles:pts[:5]: 
[[18.87161 -14.48070 20.00000]
 [16.82005 -16.82005 20.00000]
 [18.95522 -14.54485 19.10926]
 [16.89457 -16.89457 19.10926]
 [14.48070 -18.87161 20.00000]].
DEBUG:_subdivide_speckles:plane_d: -19.554630279541016.
DEBUG:_subdivide_speckles:p_center: [0.00000 0.00000 19.55463].
DEBUG:_subdivide_speckles:ref_max_pt: 87.
DEBUG:_

Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='#fefefe', position=(49999.9999…