In [1]:
from project_heart.lv import LV
import numpy as np
import pyvista as pv
pv.set_jupyter_backend("pythreejs")

import os
from pathlib import Path

from project_heart.enums import *

In [2]:
filepath = Path("../sample_files/lvhexmesh_tetcoarse_counterpart.vtk") 
lv_src = LV.from_pyvista_read(filepath)

filepath = Path("../sample_files/lvhexmesh.vtk") 
lv_dst = LV.from_pyvista_read(filepath)

In [3]:
lv_dst.regress_fibers(lv_src)

array([[ 0.43886904,  0.10513486, -0.75441977, ...,  0.82954629,
         0.61503242,  0.25418621],
       [ 0.43139718,  0.09499354, -0.76966754, ...,  0.83518818,
         0.60649865,  0.25256657],
       [ 0.42034247,  0.07767571, -0.76396612, ...,  0.84006871,
         0.58605747,  0.27385875],
       ...,
       [-0.09207854,  0.8780734 ,  0.23944282, ...,  0.98643163,
         0.1524878 ,  0.21644519],
       [-0.12218167,  0.90697469,  0.29468731, ...,  0.97764961,
         0.19295096,  0.24549067],
       [-0.10751708,  0.90822017,  0.28592666, ...,  0.97611477,
         0.18871169,  0.25472679]])

In [4]:
lv_dst.compute_fiber_angles()

In [5]:
lv_dst.plot_streamlines(LV_FIBERS.F0, scalars=LV_FIBERS.F0_ANGLES, decimate_boundary=0.8)

Renderer(camera=PerspectiveCamera(aspect=1.3333333333333333, children=(DirectionalLight(color='#fefefe', inten…

In [4]:
lv_dst.mesh.clear_data()
to_interpolate = [LV_FIBERS.F0, LV_FIBERS.S0, LV_FIBERS.N0]
lv_dst.interpolate_from_other(lv_src, to_interpolate)

array([[ 0.36349216, -0.13751394, -0.92139208, ...,  0.7643902 ,
         0.60938722,  0.2106059 ],
       [ 0.36065748, -0.13563121, -0.92278403, ...,  0.76554145,
         0.60821707,  0.20980536],
       [ 0.3615074 , -0.12937113, -0.92335016, ...,  0.771975  ,
         0.59687785,  0.21861253],
       ...,
       [-0.23657123,  0.92997088,  0.27966766, ...,  0.96735052,
         0.19929231,  0.15445711],
       [-0.25424458,  0.92125816,  0.29111517, ...,  0.9639329 ,
         0.21763387,  0.15194692],
       [-0.25036823,  0.91332002,  0.3210328 , ...,  0.96447344,
         0.20681805,  0.16338385]])

This is a wrapper function for `BaseContainerHandler.regress_from_other`. You can use the original 
function to apply regression for any data, as long as it is contained within point data or 
surface point data. Here are some examples of using the base class methods:

In [6]:
lv_dst.mesh.clear_data()
to_regress = [LV_FIBERS.F0, LV_FIBERS.S0, LV_FIBERS.N0]
lv_dst.regress_from_other(lv_src, to_regress)

array([[ 0.40326165,  0.10814094, -0.97555977, ...,  0.81008734,
         0.62364644,  0.22765032],
       [ 0.390982  ,  0.10858489, -0.97509915, ...,  0.81656445,
         0.61600243,  0.22144821],
       [ 0.38793087,  0.12357976, -0.97620715, ...,  0.82328713,
         0.6056907 ,  0.23124522],
       ...,
       [-0.31239877,  0.9756613 ,  0.22187011, ...,  1.03946484,
         0.20630184,  0.16023695],
       [-0.28181947,  1.11296013,  0.10598739, ...,  0.99408333,
         0.28398012,  0.16482965],
       [-0.26760834,  1.10557012,  0.11165132, ...,  0.99651702,
         0.26367675,  0.18271339]])

This next function we use the dst points data to regress, but we do not save at dst. It can be used to retrieve the information for some other computation.

In [10]:
lv_dst.mesh.clear_data()
to_regress = [LV_FIBERS.F0, LV_FIBERS.S0, LV_FIBERS.N0]
lv_src.regress_from_data(to_regress, lv_dst.points())

array([[ 0.39548439, -0.01185109, -0.73374947, ...,  0.79353135,
         0.55079753,  0.23242569],
       [ 0.35957941, -0.0275633 , -0.74012844, ...,  0.78753874,
         0.5640139 ,  0.23773385],
       [ 0.35333572, -0.01142629, -0.73039632, ...,  0.78477817,
         0.55304618,  0.24816431],
       ...,
       [-0.25224734,  1.08792315,  0.32901435, ...,  1.02319488,
         0.16530295,  0.12192879],
       [-0.23687494,  1.08474813,  0.27489544, ...,  1.03319214,
         0.22598994,  0.19100559],
       [-0.22066221,  1.05288314,  0.27043153, ...,  1.02583224,
         0.19841178,  0.20474248]])

The following function applies the same logic from the previous, but allows for more control over what data is being regressed, as it does not need to be contained within object

In [11]:
lv_dst.mesh.clear_data()
to_regress = [LV_FIBERS.F0, LV_FIBERS.S0, LV_FIBERS.N0]
data = lv_src.get(GEO_DATA.MESH_POINT_DATA, to_regress)
lv_src.regress_from_array(data, lv_dst.points())

array([[ 0.39635992, -0.21371164, -0.94981597, ...,  0.75609197,
         0.58704421,  0.17223183],
       [ 0.39585914, -0.21099326, -0.957215  , ...,  0.75970935,
         0.57984036,  0.17306648],
       [ 0.41189041, -0.20589557, -0.92923353, ...,  0.76535192,
         0.55973918,  0.18083946],
       ...,
       [-0.14938604,  0.91576233,  0.41052007, ...,  1.00624966,
         0.14896948,  0.1586617 ],
       [-0.22322436,  1.00423862,  0.2532364 , ...,  0.97127518,
         0.22951673,  0.17420497],
       [-0.23008209,  0.99679561,  0.28125357, ...,  0.97353358,
         0.20280966,  0.20498284]])

For more details on how the regression is performed, check `BaseContainerHandler.regress`